### ISSUE TITLE
Several python-related issues

### ISSUE THREAD

**Issue by GeoMicroSoares** [aki-559/binning-style#1]
Hi there @aki-559 @friendflower94 ,

The repository you shared in your recent preprint (https://www.biorxiv.org/content/10.1101/2021.08.09.455756v1.full.pdf) doesn't currently allow for issues to be posted. I hope I contact you via this repository even though it's not as up-to-date. 

I've been trying to run `binning-style` on the provided .fasta in the folder but have been running into a series of errors that maybe the developers could help with. I'm really excited with this project and would love to apply it to my metagenomes.

1) SyntaxError:

I have to manually remove out of place characters from `loader.py` after `git clone`.

```
$ python /home/adannehl/binning-style/main.py -l 4 -d /home/adannehl/binning-style/trainingdata_139 -c /home/adannehl/binning-style/testdata --verbose 2
Traceback (most recent call last):
  File "/home/adannehl/binning-style/main.py", line 6, in <module>
    from loader import DataLoader, read_all, to_tensor
  File "/home/adannehl/binning-style/loader.py", line 11
    \u200b
    ^
SyntaxError: invalid character in identifier
```

2) NameError:

After fixing error 1), I run into this, which is easily fixable by adding `import os` to `loader.py`.

```
$ python /home/adannehl/binning-style/main.py -l 4 -d /home/adannehl/binning-style/trainingdata_139 -c /home/adannehl/binning-style/testdata --verbose 2
Reading training data...
Traceback (most recent call last):
  File "/home/adannehl/binning-style/main.py", line 25, in <module>
    species, seqs, labels = read_all(args.dir)
  File "/home/adannehl/binning-style/loader.py", line 48, in read_all
    for i, filename in enumerate(os.listdir(dir)):
NameError: name 'os' is not defined
```

3) TypeError:

Fixing 2) gives me a TypeError which again is fixable by forcing string conversion in function `sanitize` with `str(seq)`. I don't know how correct this is, but at least it runs the script a bit further.

```
$ python /home/adannehl/binning-style/main.py -l 4 -d /home/adannehl/binning-style/trainingdata_139 -c /home/adannehl/binning-style/testdata --verbose 2
Reading training data...
Loading... 001/139Traceback (most recent call last):
  File "/home/adannehl/binning-style/main.py", line 25, in <module>
    species, seqs, labels = read_all(args.dir)
  File "/home/adannehl/binning-style/loader.py", line 52, in read_all
    name, seq = read_one(dir+"/"+filename)
  File "/home/adannehl/binning-style/loader.py", line 36, in read_one
    seq_ = sanitize(record.seq)
  File "/home/adannehl/binning-style/loader.py", line 16, in sanitize
    seq = re.sub(r"R", ["A", "G"][np.random.randint(2)], seq)
  File "/home/adannehl/miniconda3/envs/genomic_style/lib/python3.6/re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
```

4) NamerError:

This is the one I'm not really sure about. `lambda` functions have always confused me and I'm not sure what function `base.index` is.

```
$ python /home/adannehl/binning-style/main.py -l 4 -d /home/adannehl/binning-style/trainingdata_139 -c /home/adannehl/binning-style/testdata --verbose 2
Reading training data...
Loading... 001/139Traceback (most recent call last):
  File "/home/adannehl/binning-style/main.py", line 25, in <module>
    species, seqs, labels = read_all(args.dir)
  File "/home/adannehl/binning-style/loader.py", line 52, in read_all
    name, seq = read_one(dir+"/"+filename)
  File "/home/adannehl/binning-style/loader.py", line 37, in read_one
    idx = list(map(lambda b: base.index(b), seq_))
  File "/home/adannehl/binning-style/loader.py", line 37, in <lambda>
    idx = list(map(lambda b: base.index(b), seq_))
NameError: name 'base' is not defined
```

I'll keep googling about this and asking for advice in general, but if you could please help with this. Thanks so much

**Comment by aki-559** [comment]
Thank you very much for your interests in our work.
We are now examinig the problem that you raised.
We will return to you ASAP.

**Comment by aki-559** [comment]
Hi @GeoMicroSoares,
I debugged the issues you've mentioned earlier. Sorry for the inconvenience.

I checked it running on the dependencies down below. This repository is a little outdated, so please consider to update following packages.
`python = "^3.9"
torch = "^1.9.0"
biopython = "^1.79"`

Thank you again for your interests in our work. If you have any further questions, feel free to ask.

Best regards.

**Comment by GeoMicroSoares** [comment]
Hi again @aki-559 , thanks so much for this! Pulled the new version down and re-ran but unfortunately still some errors coming up that I don't know what to do with! Command and output below, any ideas?

```
$ python /home/adannehl/binning-style/main.py --layer 4 --dir WB_2019_assemblies/ --rate 0.001 --epoch 100 --verbose 2 -o WB_2019_assemblies_GS_binning
Reading fasta...
Loading... 002/002
Training model...
Traceback (most recent call last):
  File "/home/adannehl/binning-style/main.py", line 41, in <module>
    train(model, device, loader, optimizer, epoch+1)
  File "/home/adannehl/binning-style/model.py", line 11, in train
    for batch_idx, (X, y) in enumerate(loader):
  File "/home/adannehl/binning-style/loader.py", line 88, in __next__
    X_batch, y_batch = self.get_batch()
  File "/home/adannehl/binning-style/loader.py", line 111, in get_batch
    return np.apply_along_axis(crop, 1, idx.reshape(-1, 1), self.is_train), self.labels[idx]
  File "<__array_function__ internals>", line 5, in apply_along_axis
  File "/home/adannehl/miniconda3/envs/genomic_style_2/lib/python3.9/site-packages/numpy/lib/shape_base.py", line 379, in apply_along_axis
    res = asanyarray(func1d(inarr_view[ind0], *args, **kwargs))
  File "/home/adannehl/binning-style/loader.py", line 105, in crop
    start = np.random.randint(self.bounds[label] - self.length)
  File "mtrand.pyx", line 748, in numpy.random.mtrand.RandomState.randint
  File "_bounded_integers.pyx", line 1247, in numpy.random._bounded_integers._rand_int64
ValueError: high <= 0
```

**Comment by aki-559** [comment]
Hi again @GeoMicroSoares, this is caused by sampling length. which is 1024 bp by default, is longer than the length of your sequence in `WB_2019_assemblies` directory.
To tackle this, please specify `--length` argument with smaller values. Make it sure that all sequences in your fasta file are longer than the length you specified.
This can cause trouble without explicit description, so I'm going to implement checking length in future version. Anyways, I hope it helps.

Regards.

**Comment by GeoMicroSoares** [comment]
Hey again @aki-559 , tried this again a couple times with `--length` set to 1000, 999, 950 and 500, my minimum length in the assemblies in the directory being 1000bp. Still getting the same error... Any ideas to go around this?

**Comment by aki-559** [comment]
I checked it out, and I reproduced it with shorter sequences. I'm reopening the issue.
Thank you for sharing.

**Comment by aki-559** [comment]
Hi @GeoMicroSoares, I debugged the issues. Also I added some simple length-checking feature in this commit b1a07d448ee29a11bff3c492d7cfd436414ec2b8. I hope it's helpful for you.

**Comment by GeoMicroSoares** [comment]
Hey again @aki-559 , running and now on the training part (epoch 70/100 atm), but I've noticed `main.py` is running on several threads (CPU) in my server. Could you implement a thread count parameter some time in the future please? Or in the case of machines/servers with both CPUs and GPUs a parameter to define which one you want to use...
Will give updates as I get them. Cheers!

**Comment by GeoMicroSoares** [comment]
Here's the update @aki-559  - it ran until the style matrix extraction phase, which needed `test.fna`, even though `--contig` isn't a required parameter. I'm using `-d` - wouldn't that be enough to extract training data? Let me know, I can also specify one of the assemblies as training data, but would be nice if training data came from both.

**Comment by GeoMicroSoares** [comment]
Hi again @aki-559 , ran it using one of my assemblies as `-c`, got through all the train epochs, then I think during style matrix extraction it segfaulted. Ever seen this? I'm running this on a server with >40 threads, >1TB RAM, so unlikely to be a resource issue I think... Quick view of the command and output below:

```
python /home/adannehl/binning-style/main.py --layer 4 --dir WB_2019_assemblies/ --rate 0.001 --epoch 100 --length 999 --n-steps 2 --verbose 2 -o WB_2019_assemblies_GS_binning -c WB_2019_assemblies/WB_2019_0_2um_min1000.fasta
...
...
...
Train Epoch: 100 [ 00002/00002 (100%) ]  Loss: 0.0000 This took 163.109 seconds
Extracting style matrices...
Killed
```

**Comment by aki-559** [comment]
Hi @GeoMicroSoares, I added your proposal to future tasks and have some questions about the problems you're facing.

>  Or in the case of machines/servers with both CPUs and GPUs a parameter to define which one you want to use...

The device is automatically set to GPU if GPU is available from CUDA, CPU otherwise. I'm going to introduce a parameter that controls which to use.

>  I'm using -d - wouldn't that be enough to extract training data?

Train data and test data(for style matrix extraction) are expected to be different. Train data is a set of genomic fasta files, and each of them contains only one record(whole genome sequence). Test data is a file which contain multiple records, for instance, contigs. Could you tell me about file formats in your training directory? ex) single record / multiple records per file.

>  I think during style matrix extraction it segfaulted.

I've never encountered this issue. Could you provide more information about your environment so that I reproduce it and debug?

Thank you in advance.

## Tasks
- [ ] Add thread count parameter
- [x] CPU/GPU parameter

**Comment by GeoMicroSoares** [comment]
Hey again @aki-559,

Thanks so much for this - using a folder with GTDB reference genomes as training data now (one genome per file) I ran the script again only to find that function `sanitize()` in `loader.py` doesn't cover V bases (G, C or A) so I added that line of code `seq = re.sub(r"V", ["G", "C", "A"][random.randint(0, 2)], seq)` and re-running it now - maybe you want to check that for all the alternative bases below?

![image](https://user-images.githubusercontent.com/14272488/129862306-42a40f6a-51e9-406c-ad71-f7dbc3f07dc0.png)

I think the segfault was due to me using an actual genome as training data - running it again and will get back to you ASAP. 

Thanks for considering including those parameters btw - we're setting up a new machine here that has GPUs available and I'll transfer this testing there ASAP.

**Comment by GeoMicroSoares** [comment]
Hey again @aki-559 here's the latest news - all is running well until the style matrix extraction test. I've tested this on miniconda- and pip-installed packages with the same result (below). From what I can see online this might be an issue with the way data is stored temporarily in the vRAM - https://github.com/pytorch/pytorch/issues/16417. Also lower batch sizes might work but I'm not sure how to do that on my machine? Tried reducing `--length` to 500 with the same results.
Let me know if this is fixable at all... Would really like to try out your software for my data.

```
$ python3 /home/andre/binning-style/main.py -l 2 -e 5 -d /data6/databases/katharina_gtdb_allreps_min1000_subset/ -c WB_2019_assemblies/WB_2019_0_2um_min1000.fasta -o WB_2019_assemblies_GS_test/ --length 999 --device cuda --verbose 2
Reading fasta...
Loading... 500/500
Training model...
Train Epoch: 1 [ 00500/00500 (100%) ]	 Loss: 2.7926	This took 14.369 seconds
Train Epoch: 2 [ 00500/00500 (100%) ]	 Loss: 1.7424	This took 14.320 seconds
Train Epoch: 3 [ 00500/00500 (100%) ]	 Loss: 1.9511	This took 13.905 seconds
Train Epoch: 4 [ 00500/00500 (100%) ]	 Loss: 1.0389	This took 14.429 seconds
Train Epoch: 5 [ 00500/00500 (100%) ]	 Loss: 1.6125	This took 14.272 seconds
Extracting style matrices...
Traceback (most recent call last):
  File "/home/andre/binning-style/main.py", line 60, in <module>
    style_matrices += model.get_style(tensor.float().to(device), args.layer)
  File "/home/andre/binning-style/model.py", line 113, in get_style
    x = self.conv_layers[:layer](x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/batchnorm.py", line 167, in forward
    return F.batch_norm(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/functional.py", line 2281, in batch_norm
    return torch.batch_norm(
RuntimeError: CUDA out of memory. Tried to allocate 40.00 MiB (GPU 0; 15.90 GiB total capacity; 14.62 GiB already allocated; 33.12 MiB free; 14.88 GiB reserved in total by PyTorch)
```

**Comment by aki-559** [comment]
Hi @GeoMicroSoares, if it's the case, try the following solutions.

> Also lower batch sizes might work but I'm not sure how to do that on my machine?

In style matrix extraction, each sequence is converted into a tensor one by one and given to the model you've trained. So it's not that effective for your case to batchify inputs.

These are some solutions for you to try...

1. Extract style matrices inside `torch.no_grad()` block. This prevents torch to store gradients and saves some memory.
Please refer to documents [here](https://pytorch.org/docs/stable/generated/torch.no_grad.html).
2. add `.cpu()` call after `model.get_style()`. This transfers style matrix from gpu to cpu before adding it to list. This should prevent the code to store all style matrices on gpu. 

Thank you.

**Comment by GeoMicroSoares** [comment]
Hi @aki-559 , it's been some time since I've actually coded in python and I have no experience with GPU-related code - could you maybe suggest where and how in the code I could incorporate what you mention above?

**Comment by aki-559** [comment]
Hi, @GeoMicroSoares. Could you modify some lines in main.py?
ln 57 - ln 60 in main.py
```python
    with torch.no_grad():
        for record in SeqIO.parse(args.contig, "fasta"):
            tensor = to_tensor(str(record.seq))
            style_matrices += model.get_style(tensor.float().to(device), args.layer).cpu()
```

This should fix your OOM error.

**Comment by GeoMicroSoares** [comment]
Hi @aki-559 - sorry for the delay, just back from holidays... Modified those lines and run the same command but had to interrupt as it got to >1.1TB RAM with CPU - is there a way around this?

Also on GPU CUDA runs out of memory...
```
$ python3 /home/andre/binning-style/main.py -l 2 -e 5 -d /data6/databases/katharina_gtdb_allreps_min1000_subset/ -c WB_2019_assemblies/WB_2019_0_2um_min1000.fasta -o WB_2019_assemblies_GS_test/ --length 999 --device cuda --verbose 2
Reading fasta...
Loading... 500/500
Training model...
Train Epoch: 1 [ 00500/00500 (100%) ]	 Loss: 2.5307	This took 14.779 seconds
Train Epoch: 2 [ 00500/00500 (100%) ]	 Loss: 1.6422	This took 14.630 seconds
Train Epoch: 3 [ 00500/00500 (100%) ]	 Loss: 1.9425	This took 14.507 seconds
Train Epoch: 4 [ 00500/00500 (100%) ]	 Loss: 1.3647	This took 14.687 seconds
Train Epoch: 5 [ 00500/00500 (100%) ]	 Loss: 1.3603	This took 14.687 seconds
Extracting style matrices...
Traceback (most recent call last):
  File "/home/andre/binning-style/main.py", line 60, in <module>
    style_matrices += model.get_style(tensor.float().to(device), args.layer)
  File "/home/andre/binning-style/model.py", line 113, in get_style
    x = self.conv_layers[:layer](x)
  File "/home/andre/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/andre/miniconda3/lib/python3.9/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/andre/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/andre/miniconda3/lib/python3.9/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/andre/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/andre/miniconda3/lib/python3.9/site-packages/torch/nn/modules/batchnorm.py", line 167, in forward
    return F.batch_norm(
  File "/home/andre/miniconda3/lib/python3.9/site-packages/torch/nn/functional.py", line 2281, in batch_norm
    return torch.batch_norm(
RuntimeError: CUDA out of memory. Tried to allocate 40.00 MiB (GPU 0; 15.90 GiB total capacity; 14.62 GiB already allocated; 33.12 MiB free; 14.88 GiB reserved in total by PyTorch)
```
